name: easy-money-bot
channels:
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/
  - defaults
dependencies:
  - python=3.10
  - pip=23.0
  - requests=2.28.*
  - pandas=2.0.*
  - numpy=1.24.*
  - matplotlib=3.7.*
  - jupyter=1.0.*
  - pip:
    - fake-useragent==1.1.3
    - mplfinance==0.12.9b7
    - pandas-ta==0.3.14b
    - itchat==1.3.10
    - schedule==1.2.0
    - pyecharts==2.0.3  # 额外的交互式图表库
    - pillow==10.0.0    # 图像处理
    - python-dotenv==1.0.0  # 环境变量管理 